# Edite com os IPs corretos para usar em duas máquinas.
# Para testar em uma máquina só, deixe como localhost.

endereco.primario=localhost
endereco.replica=localhost

porta.clientes=5555
porta.replicacao=6000
porta.http=8080
rede.timeout.conexao.ms=3000
