# Edite com os IPs corretos para usar em duas máquinas.
# Para testar em uma máquina só, deixe como localhost.

endereco.primario=localhost
endereco.replica=localhost

porta.clientes=5555
porta.replicacao=6000
porta.http=8080
porta.discovery=5354
porta.gateway.web=8088
rede.timeout.conexao.ms=3000
rede.timeout.discovery.ms=5000
